### ISSUE TITLE
Regression in Query since 2.9.0, TypeError when querying on XHTML

### ISSUE THREAD

**Issue by zerocrates** [laminas/laminas-dom#20] opened 2022-06-06 20:42 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 2.12.0

#### Summary

Laminas\Dom\Query automatically attempts to register namespaces it finds in the root tag of an XHTML document, by regexing the tag and appending the namespace URL it finds to `$this->xpathNamespaces`. When running the query, `getNodeList()` walks through the array of namespaces and registers each one using the DOMXPath object's `registerNamespace()` method, using the array key as the prefix.

The problem is that since the "auto" namespace from the root tag is just appended to the array with `[]`, it's always a integer key, and `registerNamespace()` takes a string.

With the strict_types declaration introduced by #16, this now results in an error: Since that was merged for the 2.9.0 release, I believe this is present in all versions 2.9.0 and up.

#### Previous behavior

Previously this executed with no error.

#### Current behavior

```
TypeError: DOMXPath::registerNamespace() expects parameter 1 to be string, int given in .../vendor/laminas/laminas-dom/src/Query.php:325
Stack trace:
#0 .../vendor/laminas/laminas-dom/src/Query.php(325): DOMXPath->registerNamespace()
#1 .../vendor/laminas/laminas-dom/src/Query.php(287): Laminas\Dom\Query->getNodeList()
...
```

#### How to reproduce

To trigger this behavior, the document must begin with the `<?xml` XML prolog,  and have an `<html>` tag with an `xmlns` attribute.

```
$xhtml = '<?xml version="1.0"?><html xmlns="http://www.w3.org/1999/xhtml"></html>';
$query = new \Laminas\Dom\Query($xhtml);
$query->queryXpath('/'); // the specific query doesn't matter
```

**Comment by Ocramius** [comment] 2022-06-06 21:34
@zerocrates could you perhaps propose a failing test case + fix, since you've done the analysis?

**Comment by zerocrates** [comment] 2022-06-06 21:36
I'll look into making a PR, sure.

I think in terms of the most minimal fix we'd be looking at just casting all the prefixes to string before registering them, would that be acceptable?

**Comment by Ocramius** [comment] 2022-06-06 21:41
> just casting all the prefixes to string before registering them, would that be acceptable?

As long as the code paths where the cast is added are covered by added tests that demonstrate the necessity of such casts 👍 

That's mostly to prevent regressions when (potentially) removing them in future, via automation.

**Comment by Xerkus** [comment] 2022-06-06 23:50
Also be aware of this not-a-bug of php when dealing with array keys https://bugs.php.net/bug.php?id=80309

**Comment by Ocramius** [comment] 2022-06-07 10:04
Closing as per #21, thanks @zerocrates!

**Closed as completed by Ocramius** 2022-06-07 10:04 UTC
Labels: Bug
